export const ACTION_PREFIX = '@/template'

export const CLICK_KEY_BUTTON = 'CLICK_KEY_BUTTON'
export const CLICK_KEY_CLEAR = 'CLICK_KEY_CLEAR'
export const CLICK_KEY_CLEAR_HISTORY = 'CLICK_KEY_CLEAR_HISTORY'
export const CLICK_KEY_CLEAR_ENTRY = 'CLICK_KEY_CLEAR_ENTRY'
export const CLICK_HISTORY_ELEMENT = 'CLICK_HISTORY_ELEMENT'
export const CLICK_RESULT_BUTTON = 'CLICK_RESULT_BUTTON'
export const SWITCH_THEME = 'SWITCH_THEME'