
describe('Home page', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('check keypad buttons', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('0')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('1')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('+')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('2')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('*')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('3')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('4')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('6')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('7')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('8')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('9')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('/')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton] ')
      .contains('%')
      .click()
      .get('[data-cy=Display]')
      .contains('0-1+2*3456789/()%')
  })
  it('check sum', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('6')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('+')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('9')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('15')
  })
  it('check division', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('6')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('/')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('4')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('1.5')
  })
  it('check minus', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('7')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('9')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('-2')
  })
  it('check multiplication', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('2')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('*')
      .click({ force: true })
      .get('[data-cy=KeyButton]')
      .contains('7')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('14')
  })
  it('check remainder', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('8')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('%')
      .click({ force: true })
      .get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('3')
  })
  it('check calculate', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('*')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('.')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('3')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('+')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('6')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('/')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('3')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('+')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton]')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('*')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('(')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('1')
      .click()
      .get('[data-cy=KeyButton]')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton]')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton]')
      .contains(')')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=Display]')
      .contains('30.25')
  })
  it('clear expression', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('+')
      .click({ force: true })
      .get('[data-cy=KeyButton]')
      .contains('1')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('C')
      .click({ force: true })
      .get('[data-cy=Display]')
      .should('have.value', '')
  })

  it('clear entry', () => {
    cy.get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click({ force: true })
      .get('[data-cy=KeyButton]')
      .contains('1')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('CE')
      .click()
      .get('[data-cy=Display]')
      .contains('5-')
  })
})

describe('Settigns page', () => {
  beforeEach(() => {
    cy.visit('/settings')
  })
  it('check clear all histoty', () => {
    cy.visit('/')
      .get('[data-cy=KeyButton]')
      .contains('5')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('-')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('3')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=KeyButton]')
      .contains('=')
      .click()
      .get('[data-cy=HistoryElement]')
      .should('have.length', 2)
      .visit('/settings')
      .get('[data-cy=ControlPanel]')
      .click()
      .visit('/')
      .get('[data-cy=HistoryElement]')
      .should('have.length', 0)
  })

  it('select theme', () => {
    cy.get('[data-cy=DropDownContainer]')
      .click()
      .get('[data-cy=DropDownList]')
      .get('[data-cy=ListItem]')
      .contains('Dark theme')
      .click()
      .get('*[class^="components__Card"]')
      .should(
        'have.css',
        'background-color',
        'rgb(128, 128, 128)',
      )
  })
})